swagger: "2.0"
info:
  title: "social-media-api"
  description: "API for social media"
  contact:
    email: "naruse19910801@gmail.com"
  license:
    name: "ryo19910801/social-media-api"
    url: "https://github.com/ryo19910801/social-media-api"
basePath: "/api/v1"

securityDefinitions:
  tokenAuth:
    type: "apiKey"
    in: "header"
    name: Authorization

paths:
  /users:
    post:
      summary: users
      description: Create a user
      parameters:
        - name: user[name]
          in: formData
          description: name
          required: true
          type: string
        - name: user[self_introduction]
          in: formData
          description: self introduction
          required: false
          type: string
        - name: user[website_url]
          in: formData
          description: website url
          required: false
          type: string
        - name: user[avatar]
          in: formData
          description: avatar file
          required: false
          type: file
    patch:
      summary: users
      description: Update a user
      security:
        - tokenAuth: []
      parameters:
        - name: user[name]
          in: formData
          description: name
          required: true
          type: string
        - name: user[self_introduction]
          in: formData
          description: self introduction
          required: false
          type: string
        - name: user[website_url]
          in: formData
          description: website url
          required: false
          type: string
        - name: user[avatar]
          in: formData
          description: avatar file
          required: false
          type: file
      responses:
        200:
          description: Successfully returned a create user
          schema:
            type: "object"
            properties:
              user:
                $ref: '#/definitions/OutputUpdateUser'
    delete:
      summary: users
      description: Destroy a user
      security:
        - tokenAuth: []
      responses:
        200:
          description: Successfully a create user
          schema:
            type: object
            properties:
              message:
                type: string
                example: bye!
definitions:
  OutputCreateUser:
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      self_introduction:
        type: string
      website_url:
        type: string
      avatar:
        type: string
      auth_token:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
      avatar_url:
        type: string
  OutputUpdateUser:
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      self_introduction:
        type: string
      website_url:
        type: string
      avatar:
        type: string
      auth_token:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
      avatar_url:
        type: string
